name: Hello


on:
  
  push:
    branches: [ master ]

 
  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: windows-latest

    
    steps:
      
      - uses: actions/checkout@v2

      
      - name: welcome
        run: echo Hello, welcome to my repository