name: hello

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:

  build:
    

  steps:
    - uses: actions/checkout@v2



    - name: hello
     run: echo "Hello, welcome to my repository"